version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_gestor_test
    restart: always
    env_file:
      - ../cmd/.env
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build:
      context: .
      dockerfile: docker/Dockerfile 
    container_name: app_test_container
    restart: always
    env_file:
      - ../cmd/.env
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  mysql_data:
